import React, { useState, useEffect } from 'react';
import { useLocation, useNavigate, Link } from 'react-router-dom';
import { useLanguage } from '../../context/LanguageContext';
import { useAuth } from '../../context/AuthContext';
import api from '../../services/api';
import { AIInterpretationCard } from '../../components/customer/AIInterpretationCard';
import { SlotAndAddressStep } from '../../components/customer/SlotAndAddressStep';
import { MatchingRadarStep } from '../../components/customer/MatchingRadarStep';
import { ActiveBookingTracker } from '../../components/customer/ActiveBookingTracker';
import { FinalBillModal } from '../../components/customer/FinalBillModal';
import { MockPaymentModal } from '../../components/customer/MockPaymentModal';
import { ReviewModal } from '../../components/customer/ReviewModal';
import {
  Volume2,
  Mic,
  MicOff,
  Edit3,
  ArrowRight,
  ArrowLeft,
  CheckCircle2,
  Calendar,
  Sparkles,
  ShieldCheck,
  AlertCircle,
  Wand2,
} from 'lucide-react';

const CATEGORY_QUICK_SUGGESTIONS = {
  driver: [
    'Need a personal driver for 4 hours local city drive',
    'Airport pickup and drop driver with verified experience',
    'Full day 8-hour outstation driver requirement',
  ],
  painting: [
    'One bedroom wall repainting with fresh coat',
    'Water seepage patch repair and ceiling painting',
    'Interior apartment touchup and whitewash work',
  ],
  plumbing: [
    'Bathroom washbasin tap leaking and needs replacement',
    'Kitchen sink drain pipe clogged and overflowing',
    'Flush tank continuous water leakage repair',
  ],
  electrical: [
    'Ceiling fan making humming noise and moving slowly',
    'Switchboard loose and sparking on turning on switch',
    'Main MCB tripping repeatedly when appliance is on',
  ],
  cleaning: [
    'Deep cleaning for 2BHK apartment including bathrooms',
    'Kitchen chimney and tile grease deep cleaning',
    'Sofa and mattress vacuum shampoo wash',
  ],
  'domestic-help': [
    'Daily meal cooking help for 2 people (lunch and dinner)',
    'Utensil washing and floor mopping help for 2 hours',
    'Full day home assistance helper',
  ],
  carpentry: [
    'Wooden door lock jam and hinge alignment repair',
    'Wardrobe handle replacement and shelf fitting',
    'Bed frame squeaking noise repair',
  ],
  caregiver: [
    'Elderly care assistant for 6 hours daily support',
    'Post-surgery patient mobility and medicine assistance',
    'Daytime companion and vitals monitoring support',
  ],
  gardening: [
    'Lawn mowing, hedge trimming and garden cleanup',
    'Plant repotting, fertilization and weed removal',
    'Balcony garden setup and soil conditioning',
  ],
  'appliance-repair': [
    'Split AC not cooling properly, needs service',
    'Front load washing machine making loud vibration',
    'Microwave oven not heating food',
  ],
};

export const BookServiceWorkflow = () => {
  const { t } = useLanguage();
  const { user, profile } = useAuth();
  const location = useLocation();
  const navigate = useNavigate();

  // Initial values from navigation state or defaults
  const initialRawInput = location.state?.rawInput || '';
  const initialCategory = location.state?.category || 'electrical';

  // STEPS:
  // 1: Confirm Transcription / Request
  // 2: AI Interpretation & Rate Card Estimate
  // 3: Schedule & Address
  // 4: Matching in progress
  // 5: Active Booking (Worker Assigned & En Route & In Progress)
  // 6: Final Bill
  // 7: Mock Payment
  // 8: Review & Feedback
  // 9: Completion Summary
  const [currentStep, setCurrentStep] = useState(1);

  const [rawText, setRawText] = useState(initialRawInput);
  const [isEditingText, setIsEditingText] = useState(!initialRawInput);
  const [category, setCategory] = useState(initialCategory);

  const [scheduleData, setScheduleData] = useState({
    date: 'today',
    timeSlot: '02:00 PM - 04:00 PM',
    address: profile?.defaultAddress?.street || 'B-42, Lajpat Nagar II, New Delhi, 110024',
  });

  const [assignedWorker, setAssignedWorker] = useState(null);
  const [bookingNumber, setBookingNumber] = useState('CS-PENDING');
  const [bookingId, setBookingId] = useState(null);
  const [isAiLoading, setIsAiLoading] = useState(false);
  const [aiConfidence, setAiConfidence] = useState(0.95);
  const [detectedLanguage, setDetectedLanguage] = useState('en');

  const [minEstimate, setMinEstimate] = useState(249);
  const [maxEstimate, setMaxEstimate] = useState(499);
  const [rateCardVersion, setRateCardVersion] = useState('v2026.1');

  // Tasks generated by AI from transcription or rate card fallback
  const [parsedTasks, setParsedTasks] = useState([]);

  // Speech Recognition state
  const [isListening, setIsListening] = useState(false);
  const [micError, setMicError] = useState(null);

  const hasRealPrices = parsedTasks.some((t) => t.unitPrice != null && t.unitPrice > 0);
  const estimatedTotal = hasRealPrices
    ? parsedTasks.reduce((sum, t) => sum + (t.unitPrice || 0) * (t.quantity || 1), 0)
    : (minEstimate && minEstimate > 0 ? minEstimate : null);

  // Toggle Speech Recognition with device mic check
  const toggleSpeechRecognition = async () => {
    if (isListening) {
      if (window._cosathiRecognition) {
        try {
          window._cosathiRecognition.stop();
        } catch (e) {}
      }
      setIsListening(false);
      return;
    }

    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (!SpeechRecognition) {
      setMicError('Speech recognition is not supported in this browser. Please type below.');
      setIsEditingText(true);
      return;
    }

    try {
      if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
        try {
          const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
          stream.getTracks().forEach((track) => track.stop());
        } catch (permErr) {
          console.warn('Microphone permission error:', permErr);
          setMicError('Microphone permission was denied. Please allow mic or type your request.');
          setIsEditingText(true);
          return;
        }
      }

      setMicError(null);
      const recognition = new SpeechRecognition();
      window._cosathiRecognition = recognition;
      recognition.continuous = false;
      recognition.interimResults = true;
      recognition.lang = 'hi-IN';

      recognition.onstart = () => {
        setIsListening(true);
      };

      recognition.onresult = (ev) => {
        const transcript = Array.from(ev.results)
          .map((r) => r[0].transcript)
          .join('');
        if (transcript) {
          setRawText(transcript);
        }
      };

      recognition.onerror = (err) => {
        console.warn('Speech recognition error:', err.error);
        setIsListening(false);
        if (err.error === 'not-allowed') {
          setMicError('Microphone permission blocked. Please allow mic in browser settings.');
        } else if (err.error === 'no-speech') {
          setMicError('No voice detected. Please tap again and speak into mic.');
        } else {
          setMicError(`Voice input issue (${err.error}). Please type below.`);
        }
        setIsEditingText(true);
      };

      recognition.onend = () => {
        setIsListening(false);
      };

      recognition.start();
    } catch (e) {
      console.error('Speech start error:', e);
      setIsListening(false);
      setMicError('Unable to start speech recognition. Please type your request.');
      setIsEditingText(true);
    }
  };

  // Step 1 -> Step 2 (Invokes Google Gemini Server-side AI Interpretation + Rate Card Estimation)
  const handleConfirmTranscription = async () => {
    if (!rawText.trim()) return;
    setIsAiLoading(true);
    try {
      const res = await api.post('/ai/interpret-request', { text: rawText, category });
      if (res.data?.success && res.data?.data) {
        const aiData = res.data.data;
        if (aiData.serviceCategory) setCategory(aiData.serviceCategory);
        if (aiData.confidence) setAiConfidence(aiData.confidence);
        if (aiData.language) setDetectedLanguage(aiData.language);

        if (Array.isArray(aiData.tasks) && aiData.tasks.length > 0) {
          // Reconcile Gemini tasks against MongoDB RateCard for authoritative pricing
          try {
            const tasksWithCategory = aiData.tasks.map((t) => ({
              ...t,
              categorySlug: aiData.serviceCategory || category,
              serviceCategory: aiData.serviceCategory || category,
            }));
            const estRes = await api.post('/rate-card/estimate', { tasks: tasksWithCategory });
            if (estRes.data?.success && estRes.data?.data) {
              const est = estRes.data.data;
              setParsedTasks(
                est.items.map((it) => ({
                  code: it.code,
                  title: it.name || it.title,
                  quantity: it.quantity || 1,
                  unitPrice: it.unitPrice,
                  minPrice: it.minPrice,
                  maxPrice: it.maxPrice,
                }))
              );
              setMinEstimate(est.minEstimate);
              setMaxEstimate(est.maxEstimate);
              setRateCardVersion(est.rateCardVersion || 'v2026.1');
            }
          } catch (estErr) {
            console.warn('[Workflow] Deterministic rate card estimate notice:', estErr.message);
            const mapped = aiData.tasks.map((t, idx) => ({
              code: t.code,
              title: t.label || t.title || `${category} Service #${idx + 1}`,
              quantity: 1,
              unitPrice: t.estimatedPrice || null,
              minPrice: null,
              maxPrice: null,
            }));
            setParsedTasks(mapped);
          }
        }
      }
    } catch (err) {
      console.warn('[Workflow] Gemini API interpretation notice:', err.message);
      // Clean fallback according to chosen category
      setParsedTasks([
        {
          code: `${category.toUpperCase().replace(/-/g, '_')}_SERVICE`,
          title: `${category.charAt(0).toUpperCase() + category.slice(1).replace(/-/g, ' ')} Cooperative Service`,
          quantity: 1,
          unitPrice: null,
          minPrice: null,
          maxPrice: null,
        },
      ]);
    } finally {
      setIsAiLoading(false);
      setCurrentStep(2);
    }
  };

  // Step 2 -> Step 3
  const handleProceedToSchedule = () => {
    setCurrentStep(3);
  };

  // Step 3 -> Step 4
  const handleConfirmSchedule = async (data) => {
    setScheduleData(data);
    setCurrentStep(4); // Start matching

    try {
      const targetCoords = data.coordinates || [77.2433, 28.5700];
      const res = await api.post('/bookings', {
        serviceCategory: category || 'electrical',
        tasks: parsedTasks.map((t) => ({
          title: t.title,
          serviceCode: t.code,
          quantity: t.quantity,
          estimatedPrice: t.unitPrice,
        })),
        voiceTranscript: rawText,
        initialEstimate: estimatedTotal || 199,
        address: {
          addressLine: data.address || 'B-42, Lajpat Nagar II, New Delhi',
          city: 'Delhi',
          pincode: '110024',
        },
        location: {
          type: 'Point',
          coordinates: targetCoords,
        },
      });

      if (res.data?.success && res.data?.booking) {
        setBookingId(res.data.booking._id);
        setBookingNumber(res.data.booking.bookingNumber);
      }
    } catch (err) {
      console.warn('[Workflow] Auto-creating backend booking notice:', err.response?.data?.message || err.message);
      if (err.response?.data?.conflictBookingId) {
        setBookingId(err.response.data.conflictBookingId);
        if (err.response.data.conflictBookingNumber) {
          setBookingNumber(err.response.data.conflictBookingNumber);
        }
      }
    }
  };

  // Step 4 -> Step 5 (Worker matched)
  const handleWorkerMatched = (worker) => {
    setAssignedWorker(worker);
    setCurrentStep(5); // Active booking
  };

  // Step 5 -> Step 6 (Work finished)
  const handleJobCompleted = () => {
    setCurrentStep(6); // Final Bill
  };

  // Step 6 -> Step 7
  const handleProceedToPayment = () => {
    setCurrentStep(7); // Mock Payment
  };

  // Step 7 -> Step 8
  const handlePaymentComplete = (txnId) => {
    setCurrentStep(8); // Review
  };

  // Step 8 -> Complete & Save to History
  const handleSubmitReview = async (reviewData) => {
    try {
      if (bookingId) {
        await api.post(`/bookings/${bookingId}/review`, reviewData);
      }
    } catch (err) {
      console.warn('Review API submission warning:', err.response?.data?.message || err.message);
    }

    // Save to local storage for demo history
    const existingHistory = JSON.parse(localStorage.getItem('cosathi_history') || '[]');
    const newRecord = {
      bookingNumber,
      category,
      date: new Date().toLocaleDateString('en-IN'),
      workerName: assignedWorker?.name || 'Cooperative Sathi',
      amount: estimatedTotal,
      status: 'completed',
      serviceTitle: parsedTasks[0]?.title || `${category} Service`,
      review: reviewData,
    };
    localStorage.setItem('cosathi_history', JSON.stringify([newRecord, ...existingHistory]));

    setCurrentStep(9);
  };

  return (
    <div className="max-w-3xl mx-auto space-y-6 pb-16">
      {/* Top Bar with < Back and Home (Screenshot 3) */}
      <div className="flex items-center justify-between px-1">
        <button
          onClick={() => {
            if (currentStep > 1) setCurrentStep(currentStep - 1);
            else navigate('/customer/home');
          }}
          className="flex items-center space-x-1.5 text-xs sm:text-sm font-semibold text-[#122A4E] hover:text-[#1B4278] transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back</span>
        </button>

        <Link
          to="/customer/home"
          className="flex items-center space-x-1.5 text-xs sm:text-sm font-medium text-[#636D79] hover:text-[#20242A] transition-colors"
        >
          <span>Home</span>
        </Link>
      </div>

      {/* Horizontal Stepper (Screenshot 3: Request -> Understanding -> Schedule -> Matching -> Assigned) */}
      <div className="bg-white rounded-xl p-3 sm:p-4 border border-[#D9D5CC] shadow-xs">
        <div className="flex items-center justify-between text-[11px] sm:text-xs font-semibold">
          {[
            { step: 1, label: 'Request' },
            { step: 2, label: 'Understanding' },
            { step: 3, label: 'Schedule' },
            { step: 4, label: 'Matching' },
            { step: 5, label: 'Assigned' },
          ].map((item, idx, arr) => {
            const isActive = currentStep === item.step;
            const isCompleted = currentStep > item.step;

            return (
              <React.Fragment key={item.step}>
                <div
                  className={`flex flex-col items-center cursor-pointer ${
                    isActive
                      ? 'text-[#9E472A] font-bold'
                      : isCompleted
                      ? 'text-[#122A4E] font-medium'
                      : 'text-slate-400 font-normal'
                  }`}
                  onClick={() => {
                    if (isCompleted) setCurrentStep(item.step);
                  }}
                >
                  <span className="tracking-tight">{item.label}</span>
                  {isActive && <span className="w-6 h-0.5 bg-[#9E472A] mt-1 rounded-full"></span>}
                </div>
                {idx < arr.length - 1 && (
                  <span className="text-slate-300 font-normal select-none">›</span>
                )}
              </React.Fragment>
            );
          })}
        </div>
      </div>

      {/* STEP 1: Confirm Transcription / Request (Screenshot 3 style) */}
      {currentStep === 1 && (
        <div className="bg-white rounded-2xl sm:rounded-3xl p-6 sm:p-10 border border-[#D9D5CC] shadow-card text-center space-y-6">
          <div className="space-y-1">
            <h2 className="font-serif text-2xl sm:text-3xl font-bold text-[#20242A]">
              Tell us what's wrong
            </h2>
            <p className="text-xs sm:text-sm text-[#636D79]">
              Selected trade: <span className="font-semibold text-[#122A4E] capitalize">{category}</span> • Speak or type in Hindi or English
            </p>
          </div>

          {/* Large Circular Voice Button with Live Pulse Animation */}
          <div className="py-2 flex flex-col items-center justify-center space-y-3">
            <div className="relative">
              {isListening && (
                <>
                  <span className="absolute -inset-3 rounded-full bg-red-400 opacity-75 animate-ping"></span>
                  <span className="absolute -inset-1 rounded-full bg-red-500 opacity-50 animate-pulse"></span>
                </>
              )}
              <button
                type="button"
                onClick={toggleSpeechRecognition}
                className={`relative w-24 h-24 sm:w-28 sm:h-28 rounded-full flex items-center justify-center shadow-xl transition-all focus:outline-none ${
                  isListening
                    ? 'bg-red-600 hover:bg-red-700 text-white scale-105 shadow-red-300'
                    : 'bg-[#1B4278] hover:bg-[#122A4E] text-white hover:scale-105 shadow-blue-200'
                }`}
                title={isListening ? 'Tap to stop listening' : 'Click to speak'}
                aria-label={isListening ? 'Stop listening' : 'Start speaking'}
              >
                {isListening ? (
                  <MicOff className="w-10 h-10 sm:w-12 sm:h-12 text-white animate-bounce" />
                ) : (
                  <Mic className="w-10 h-10 sm:w-12 sm:h-12 text-white" />
                )}
              </button>
            </div>

            <div className="space-y-1">
              <span className={`text-xs sm:text-sm font-serif font-bold ${isListening ? 'text-red-600 animate-pulse' : 'text-[#20242A]'}`}>
                {isListening ? 'Listening... Speak now (Hindi or English)' : 'Tap and speak — or select a common request below'}
              </span>
              {isListening && (
                <p className="text-[11px] text-slate-500 font-medium">Tap microphone again when you finish speaking</p>
              )}
            </div>
          </div>

          {micError && (
            <div className="p-3 rounded-xl bg-amber-50 border border-amber-200 text-amber-800 text-xs flex items-center space-x-2 text-left">
              <AlertCircle className="w-4 h-4 shrink-0 text-amber-600" />
              <span className="flex-1">{micError}</span>
            </div>
          )}

          {/* Quick Problem Suggestions for Category */}
          {CATEGORY_QUICK_SUGGESTIONS[category] && (
            <div className="space-y-2 text-left bg-[#F7F4EE] p-4 rounded-2xl border border-[#D9D5CC]">
              <span className="text-xs font-semibold text-[#636D79] flex items-center space-x-1.5">
                <Wand2 className="w-3.5 h-3.5 text-[#9E472A]" />
                <span className="capitalize">Common {category} requests (Tap to fill):</span>
              </span>
              <div className="flex flex-wrap gap-2 pt-1">
                {CATEGORY_QUICK_SUGGESTIONS[category].map((prompt, idx) => (
                  <button
                    key={idx}
                    type="button"
                    onClick={() => {
                      setRawText(prompt);
                      setIsEditingText(false);
                      setMicError(null);
                    }}
                    className={`text-xs px-3 py-1.5 rounded-full border text-left transition-all ${
                      rawText === prompt
                        ? 'bg-[#122A4E] text-white border-[#122A4E] shadow-xs'
                        : 'bg-white hover:bg-slate-50 text-[#20242A] border-[#D9D5CC]'
                    }`}
                  >
                    + {prompt}
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Captured Requirement Preview */}
          <div className="p-5 rounded-2xl bg-white border border-[#D9D5CC] shadow-xs space-y-3 text-left">
            <div className="flex items-center justify-between text-xs font-semibold text-[#636D79]">
              <span className="flex items-center space-x-1.5">
                <span className={`w-2 h-2 rounded-full ${rawText.trim() ? 'bg-[#3C5A48]' : 'bg-amber-400'}`}></span>
                <span>Service Request Details</span>
              </span>
              <button
                type="button"
                onClick={() => setIsEditingText(!isEditingText)}
                className="text-[#9E472A] hover:underline flex items-center space-x-1"
              >
                <Edit3 className="w-3.5 h-3.5" />
                <span>{isEditingText ? 'Done' : 'Type / Edit'}</span>
              </button>
            </div>

            {isEditingText ? (
              <textarea
                rows={3}
                value={rawText}
                onChange={(e) => setRawText(e.target.value)}
                className="w-full p-3 text-sm rounded-xl border border-[#D9D5CC] focus:outline-none focus:border-[#1B4278] bg-[#F7F4EE] text-[#20242A]"
                placeholder="उदा. बाथरूम का नल बदलना है या ड्राइवर चाहिए..."
              />
            ) : rawText.trim() ? (
              <p className="text-sm sm:text-base font-serif text-[#20242A] italic leading-relaxed">
                "{rawText}"
              </p>
            ) : (
              <p className="text-sm font-sans text-slate-400 italic">
                Tap microphone to speak or click one of the suggestions above.
              </p>
            )}
          </div>

          <div className="flex justify-end pt-2">
            <button
              onClick={handleConfirmTranscription}
              disabled={isAiLoading || !rawText.trim()}
              className="w-full sm:w-auto px-8 py-3 bg-[#9E472A] hover:bg-[#853920] text-white font-bold rounded-xl text-sm shadow-md transition-all flex items-center justify-center space-x-2 disabled:opacity-50"
            >
              {isAiLoading ? (
                <>
                  <Sparkles className="w-4 h-4 animate-spin text-amber-200" />
                  <span>Analyzing with Gemini AI...</span>
                </>
              ) : (
                <>
                  <span>Continue to AI Understanding</span>
                  <ArrowRight className="w-4 h-4" />
                </>
              )}
            </button>
          </div>
        </div>
      )}

      {/* STEP 2: AI Interpretation & Rate Card Estimate */}
      {currentStep === 2 && (
        <div className="space-y-6">
          <AIInterpretationCard
            parsedTasks={parsedTasks}
            estimatedTotal={estimatedTotal}
            minEstimate={minEstimate}
            maxEstimate={maxEstimate}
            rateCardVersion={rateCardVersion}
            rawRequirement={rawText}
            confidence={aiConfidence}
            languageDetected={detectedLanguage}
            category={category}
          />

          <div className="flex items-center justify-between">
            <button
              onClick={() => setCurrentStep(1)}
              className="px-5 py-2.5 rounded-xl border border-cosathi-border text-xs font-bold text-cosathi-slate hover:bg-cosathi-surface"
            >
              {t('common.back')}
            </button>
            <button
              onClick={handleProceedToSchedule}
              className="px-6 py-3 bg-cosathi-forest hover:bg-cosathi-forest-dark text-white text-sm font-bold rounded-xl shadow-md transition-all flex items-center space-x-2"
            >
              <span>Select Date & Address →</span>
            </button>
          </div>
        </div>
      )}

      {/* STEP 3: Slot & Address Selection */}
      {currentStep === 3 && (
        <SlotAndAddressStep
          initialAddress={scheduleData.address}
          onConfirmSchedule={handleConfirmSchedule}
          onBack={() => setCurrentStep(2)}
        />
      )}

      {/* STEP 4: Matching in Progress */}
      {currentStep === 4 && (
        <MatchingRadarStep
          bookingId={bookingId}
          onMatched={handleWorkerMatched}
          onCancel={() => navigate('/customer/home')}
        />
      )}

      {/* STEP 5: Active Booking Tracker & Worker Revealed */}
      {currentStep === 5 && (
        <ActiveBookingTracker
          bookingData={{ _id: bookingId, bookingNumber }}
          workerData={assignedWorker}
          onCompleteJob={handleJobCompleted}
          onCancelBooking={() => navigate('/customer/home')}
        />
      )}

      {/* STEP 6: Final Bill Reconciled against Rate Card */}
      {currentStep === 6 && (
        <FinalBillModal
          billItems={parsedTasks}
          grossTotal={estimatedTotal}
          onProceedToPayment={handleProceedToPayment}
        />
      )}

      {/* STEP 7: Mock Payment */}
      {currentStep === 7 && (
        <MockPaymentModal
          amount={estimatedTotal}
          onPaymentComplete={handlePaymentComplete}
        />
      )}

      {/* STEP 8: Review & Feedback */}
      {currentStep === 8 && (
        <ReviewModal
          workerName={assignedWorker?.name || 'Cooperative Sathi'}
          onSubmitReview={handleSubmitReview}
        />
      )}

      {/* STEP 9: Final Success / Completed Screen */}
      {currentStep === 9 && (
        <div className="bg-white rounded-3xl p-8 border border-cosathi-border shadow-sm text-center space-y-6 max-w-lg mx-auto">
          <div className="w-16 h-16 rounded-full bg-emerald-100 text-emerald-600 flex items-center justify-center mx-auto shadow-inner">
            <CheckCircle2 className="w-10 h-10" />
          </div>

          <div className="space-y-2">
            <h3 className="text-2xl font-bold text-cosathi-slate">Service Successfully Completed!</h3>
            <p className="text-xs text-cosathi-muted">
              {t('customer.thankYou')}
            </p>
          </div>

          <div className="p-4 rounded-2xl bg-cosathi-surface border border-cosathi-border text-left text-xs space-y-1.5">
            <div className="flex justify-between font-bold">
              <span>Booking Ref:</span>
              <span className="font-mono text-cosathi-forest">{bookingNumber}</span>
            </div>
            <div className="flex justify-between text-cosathi-muted">
              <span>Cooperative Sathi:</span>
              <span className="font-semibold text-cosathi-slate">{assignedWorker?.name}</span>
            </div>
            <div className="flex justify-between text-cosathi-muted">
              <span>Total Settled:</span>
              <span className="font-semibold text-cosathi-forest">
                {estimatedTotal != null ? `₹${estimatedTotal}` : 'On-site estimate'}
              </span>
            </div>
          </div>

          <div className="flex gap-3">
            <button
              onClick={() => navigate('/customer/history')}
              className="flex-1 py-3 bg-cosathi-surface hover:bg-cosathi-border/30 border border-cosathi-border text-cosathi-slate text-xs font-bold rounded-xl transition-all"
            >
              View in History
            </button>
            <button
              onClick={() => navigate('/customer/home')}
              className="flex-1 py-3 bg-cosathi-forest hover:bg-cosathi-forest-dark text-white text-xs font-bold rounded-xl shadow-md transition-all"
            >
              Back to Home
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
